emoji_sentiment = {'😷': -1,
                   '❤': 1,
                   '😉': 1,
                   '♥': 1,
                   '😂': 1,
                   '😳': -1,
                   '💫': 1,
                   '😭': -1,
                   '😔': -1,
                   '☺': 1,
                   '😩': -1,
                   '😘': -1,
                   '😊': 1,
                   '😆': 1,
                   '🌟': 1,
                   '⛄': 1,
                   '😚': -1,
                   '😅': 1,
                   '👍': 1,
                   '😏': -1,
                   '😯': 1,
                   '😒': -1,
                   '💃': 1,
                   '😡': -1,
                   '🎂': 1,
                   '🎉': 1,
                   '👋': 1,
                   '😎': 1,
                   '😜': 1,
                   '👌': 1,
                   '😍': 1,
                   '💚': 1,
                   '💕': 1,
                   '😁': -1,
                   '👏': 1,
                   '🍷': 1,
                   '💛': 1,
                   '😄': 1,
                   '✅': 1,
                   '😝': 1,
                   '😺': 1,
                   '🎁': 1,
                   '😞': -1,
                   '😥': -1,
                   '☹': -1,
                   '💯': 1,
                   '😢': -1,
                   '💗': 1,
                   '✌': 1,
                   '😫': -1,
                   '💟': -1,
                   '😬': -1,
                   '💜': 1,
                   '😃': 1,
                   '😵': -1,
                   '👭': 1,
                   '🙀': 1,
                   '😀': 1,
                   '👎': -1,
                   '💞': 1,
                   '😤': -1,
                   '💖': 1,
                   '😋': 1,
                   '😴': -1,
                   '😦': -1,
                   '😓': -1,
                   '😗': 1,
                   '💔': -1,
                   '😐': -1,
                   '😨': -1,
                   ':)': 1,
                   ':(': -1,
                   ':P': 1,
                   ';)': 1,
                   '(y)': 1}

interjections = ['wow', 'haha', 'lol', 'rofl', 'lmao', 'kidding', 'wtf', 'duh', 'ha ha']
exclude = ['I', 'U.S']
intensifier_list = ['absolutely', 'amazingly', 'awfully', 'completely', 'considerably', 'decidedly', 'deeply', 'effing',
                    'enormously', 'entirely', 'especially', 'exceptionally', 'extremely',
                    'fabulously', 'flipping', 'flippin', 'fricking', 'frigging', 'friggin', 'fully', 'fucking',
                    'greatly', 'highly', 'hugely', 'incredibly', 'intensely', 'majorly', 'more', 'most', 'particularly',
                    'purely', 'quite', 'really', 'remarkably', 'so', 'substantially', 'thoroughly', 'totally',
                    'tremendously', 'unbelievably', 'unusually', 'utterly', 'very', 'almost', 'barely', 'hardly',
                    'just enough', 'kind of', 'kinda', 'less', 'little']

popular_emoji = ['❤',
                 '😉',
                 '😂',
                 '😭',
                 '😔',
                 '☺',
                 '😩',
                 '😘',
                 '😆',
                 '😚',
                 '👍',
                 '😏',
                 '😒',
                 '😡',
                 '😎',
                 '😜',
                 '😍',
                 '😄',
                 '😝',
                 '😞',
                 '☹',
                 '😢',
                 '😫',
                 '😬',
                 '😃',
                 '😴',
                 '😓',
                 '😗',
                 '💔',
                 '😐',
                 ':)',
                 ':(',
                 ':P',
                 ';)',
                 '(y)', ]
